In [25]:
#Ctrl+Enter：只运行当前节即停止；Ctrl+Shift+Enter：运行当前节及其下方所有节
#Ctrl+Alt+Enter：运行当前节及其上方所有节；Shift+Enter：运行当前节并跳转到下一节
#Ctrl+S：保存当前文件；Ctrl+F5：运行当前文件
import torch

In [4]:
x=torch.arange(12)    #张量表示一个数值组成的数组，这个数组可能有多个维度
x    #x是张量类torch.arange的一个实例化对象

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x.shape    #可以通过张量类torch.arange的 shape 属性访问张量的形状&张量中元素的个数

torch.Size([12])

In [6]:
x.numel()    #张量类torch.arange的方法numel()：number of element，即元素总数

12

In [7]:
X=x.reshape(3,4)    #要改变一个张量的形状而不改变元素数量和元素值
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.zeros((2,3,4))    #使用全0的2层、3行、4列三维矩阵

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2,3,4))    #使用全1的2层、3行、4列三维矩阵

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])    #通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋值

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [11]:
x=torch.tensor([1,2,4,8])    #标准算术运算符被升级为按元素运算
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [12]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)    #torch.cat可将多个向量连接在一起，dim=0按第0维行来相连；dim=1按第1维列来相连

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
X==Y    #通过逻辑运算符构建二维张量

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
X.sum()    #对张量中所有元素求和，会产生一个只有一个元素的张量

tensor(66.)

In [15]:
a=torch.arange(3).reshape((3,1))    #列扩充为2列
b=torch.arange(2).reshape((1,2))    #行扩充为3行
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
a+b    #即使两个张量形状不同，仍可通过调用广播机制（Numpy中也有）来执行按元素操作

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [17]:
X[-1],X[1:3]    #下标从开始；[-1]选择该维度最后一个元素；[1:3]选择第2个和第3个元素（下标为1～下标为3-1=2）

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[1,2]=9    #除读取外，还可以通过指定索引来将元素写入矩阵
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
X[0:2,:]=12    #使用Python的切片语法[m:n]为多个元素赋值
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [24]:
before=id(Y)    #运行一些操作可能会导致为新结果分配内存（运算符重载）
Y=Y+X    #PyTorch的Tensor张量是可变类型（可通过索引修改）其形状和数据类型不可变；Y=Y+X则会新建一个新的Tensor对象（本质是产生一个新的Y）；Y[:]=Y+X和Y+=X则不会（本质是给Y的各元素赋值）
# Y+=X    #减少内存开销
id(Y)==before

False

In [21]:
Z=torch.zeros_like(Y)    #执行原地操作
print('id(Z):',id(Z))
Z[:]=X+Y    #减少内存开销
print('id(Z):',id(Z))    #对其修改并没有新建一个新的Tensor对象

id(Z): 140357695176144
id(Z): 140357695176144


In [22]:
A=X.numpy()    #Tensor张量转换为NumPy张量
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
a=torch.tensor([3.5])    #将大小为1的张量转换为Python标量
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)