In [2]:
import torch
print(torch.cuda.is_available()) # 应该返回 True
print(torch.cuda.device_count()) # 应该显示您的GPU数量
print(torch.cuda.get_device_name(0)) # 应该显示您的GPU名称

True
1
AMD Radeon RX 6700 XT


In [3]:
# 标量由只有一个元素的张量表示
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [4]:
# 将向量视作标量值组成的列表
x=torch.arange(4,dtype=torch.int32) # 创建一个包含0到3的整数向量
print(x) # 输出 tensor([0, 1, 2, 3])
print(x[3]) # 通过索引访问张量元素

tensor([0, 1, 2, 3], dtype=torch.int32)
tensor(3, dtype=torch.int32)


In [5]:
# 访问张量的长度
print(len(x)) # 输出 4
# 访问张量的形状
print(x.shape) # 输出 torch.Size([4])；只有一个轴的张量，形状只有一个元素（一个维度）

4
torch.Size([4])


In [6]:
# 通过指定两个分量m，n创建一个形状为(m,n)的矩阵
A=torch.arange(20).reshape(5,4) # A是一个5行4列的矩阵
print(A)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


In [7]:
# 矩阵的转置
print(A.T) # 输出转置后的矩阵

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [8]:
# 对称矩阵的转置等于它本身
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B.T) # 输出转置后的矩阵
print(B==B.T) # 检查B是否等于B的转置，返回布尔值（会对应每个元素进行比较）

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [9]:
# 向量是标量的推广，矩阵是向量的推广
X=torch.arange(24).reshape(2,3,4) # 形状为(2,3,4)的三维张量，（最外层维度,...,最内层维度）
print(X.shape) # 输出 torch.Size([2, 3, 4])
print(X)
# 计算张量元素的和
print(X.sum()) # 输出张量X所有元素的和

torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor(276)


In [23]:
# 给定具有相同形状的任意两个向量，任何按元素二元运算都可以通过广播机制自动扩展为相同形状的张量进行计算。
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() # 克隆A，B与A具有相同的形状、值、内存地址
print(A) # 输出A
print(A+B) # 输出按元素和A+B，A+B的形状与A和B相同

# 沿着矩阵某个轴求和
A_sum_axis0=A.sum(axis=0) # 沿着第0轴（行）求和，则行数变为1，列数保持不变
A_sum_axis1=A.sum(axis=1) # 沿着第1轴（列）求和，则行数保持不变，列数变为1
print(A_sum_axis0,A_sum_axis0.shape) # 输出沿着第0轴求和后的结果，以及它的形状
print(A_sum_axis1,A_sum_axis1.shape) # 输出沿着第1轴求和后的结果，以及它的形状

# 求平均值，mean()函数默认沿着所有轴求平均值
print(A.mean(),A.sum()/A.numel()) # 输出平均值，numel()返回张量的元素总数
# 计算总和或均值时保持轴数不变
sum_axis0=A.sum(axis=0) # 沿着第0轴求和，保持轴数不变
print(sum_axis0) # 沿着第0轴求和，保持轴数不变
print(A/sum_axis0) # 将A除以sum_axis0（广播机制）
# A按某个轴计算元素的总和
A.cumsum(axis=0) # 沿着第0轴计算元素的总和，返回一个新的张量

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])
tensor([40., 45., 50., 55.]) torch.Size([4])
tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])
tensor(9.5000) tensor(9.5000)
tensor([40., 45., 50., 55.])
tensor([[0.0000, 0.0222, 0.0400, 0.0545],
        [0.1000, 0.1111, 0.1200, 0.1273],
        [0.2000, 0.2000, 0.2000, 0.2000],
        [0.3000, 0.2889, 0.2800, 0.2727],
        [0.4000, 0.3778, 0.3600, 0.3455]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [ ]:
# 点积：相同位置按元素乘积的和
y=torch.ones(4,dtype=torch.int32) # 创建一个全1的整数型向量
print(x) # 输出向量x
print(torch.dot(x,y)) # 输出x和y的点积

# 哈达玛积（注意不等于矩阵乘法）:两个矩阵的按元素乘法
# 这里的按元素乘法是指对应位置的元素相乘
print(x*y) # 输出x和y的哈达玛积（按元素乘法）的和
print(torch.sum(x*y)) # 先进行哈达玛积，然后求和，等同于点积

# 按元素加法和乘法
a=2
X=torch.arange(24).reshape(2,3,4) # 形状为(2,3,4)的三维张量
print(X) # 输出按元素和X+a，X+a的形状与X相同
print(X+a) # 输出按元素和X+a，X+a的形状与X相同
print(X*a,(X*a).shape,sep="\n") # 输出按元素积X*a，X*a的形状

# 矩阵向量积Ax
A=torch.arange(20,dtype=torch.int32).reshape(5,4) # 创建一个5行4列的矩阵
print(A) # 输出矩阵A的形状
print(x) # 输出向量x的形状
print(torch.mv(A,x)) # 输出矩阵A和向量x的矩阵向量积

# 矩阵乘法AB：执行m次矩阵向量积，并将结果组合成一个n*m矩阵
B=torch.ones(4,3,dtype=torch.int32) # 创建一个4行3列的矩阵
print(A) # 输出矩阵A
print(B) # 输出矩阵B
print(torch.mm(A,B)) # 输出矩阵A和矩阵B的矩阵乘

tensor([0, 1, 2, 3], dtype=torch.int32)
tensor(6, dtype=torch.int32)
tensor([0, 1, 2, 3], dtype=torch.int32)
tensor(6)
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],

        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]])
tensor([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],

        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])
torch.Size([2, 3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=torch.int32)
tensor([0, 1, 2, 3], dtype=torch.int32)
tensor([ 14,  38,  62,  86, 110], dtype=torch.int32)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 1

In [27]:
# L1范数：向量元素绝对值之和
u=torch.tensor([3.0,-4.0]) # 创建一个向量u
print(torch.norm(u, p=1)) # 写法1：输出向量u的L1范数

# L2范数：向量元素平方和的平方根
u=torch.tensor([3.0,-4.0]) # 创建一个向量u
print(torch.norm(u, p=2)) # 写法1：输出向量u的L2范数
print(torch.norm(u)) # 写法2：输出向量u的L2范数

# 弗罗贝尼乌斯范数：矩阵元素平方和的平方根
A=torch.arange(20,dtype=torch.float32).reshape(5,4) # 创建一个5行4列的矩阵
print(torch.norm(A, p='fro')) # 写法1：输出矩阵A的弗罗贝尼乌斯范数
print(torch.norm(A, p='fro')) # 写法1：输出矩阵A的弗罗贝尼乌斯范数
print(torch.norm(A)) # 写法2：输出矩阵A的弗罗贝尼乌斯范数

tensor(7.)
tensor(5.)
tensor(5.)
tensor(49.6991)
tensor(49.6991)
tensor(49.6991)


In [28]:
a=torch.ones((2,5,4),dtype=torch.int32) # 创建一个形状为(2,5,4)的张量
print(a.shape) # 输出张量a的形状
print(a.sum(), a.sum().shape) # 输出张量a的内容，以及所有元素的和的形状，应该是一个标量，所以形状是torch.Size([])
print(a.sum(axis=0), a.sum(axis=0).shape) # 沿着第0轴求和，返回一个新的张量(5,4)
print(a.sum(axis=1), a.sum(axis=1).shape) # 沿着第1轴求和，返回一个新的张量(2,4)
print(a.sum(axis=2), a.sum(axis=2).shape) # 沿着第2轴求和，返回一个新的张量(2,5)
print(a.sum(axis=[0,1]),a.sum(axis=[0,1]).shape) # 沿着第0轴和第1轴求和，返回一个新的张量(4,)
print(a.sum(axis=1,keepdim=True),a.sum(axis=1,keepdim=True).shape) # 沿着第0轴和第2轴求和，返回一个新的张量(5,)

torch.Size([2, 5, 4])
tensor(40) torch.Size([])
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]) torch.Size([5, 4])
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5]]) torch.Size([2, 4])
tensor([[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]) torch.Size([2, 5])
tensor([10, 10, 10, 10]) torch.Size([4])
tensor([[[5, 5, 5, 5]],

        [[5, 5, 5, 5]]]) torch.Size([2, 1, 4])
