In [7]:
import numpy as np

# 默认数据类型为浮点数
ar1=np.zeros(5)
print(ar1)

# 设置为整形
ar2=np.zeros(5,dtype='int')
print(ar2)

# 2行2列的全0数组
ar3=np.zeros((2,2))
print(ar3)

# zero_like返回具有与给定数组相同形状、类型的全0数组
ar=np.array([[1,2,3],[4,5,6]])
ar4=np.zeros_like(ar)
print(ar4)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0. 0.]
 [0. 0.]]
[[0 0 0]
 [0 0 0]]


In [8]:
# 全1数列
ar5=np.ones(9)
print(ar5)

ar6=np.ones((2,3,4))
print(ar6)

ar7=np.ones_like(ar)
print(ar7)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[1 1 1]
 [1 1 1]]
