In [34]:
# 1.numpy自带的各种数据类型：
# bool_/bool8：布尔型数据类型（True/False）
# int：默认整数类型，类似C语言中的long、int32、int64
# intc：和C语言的int类型一样，一般是int32或int64
# intp：用于索引的整数类型，类似C语言的ssize_t，通常是int32或int64
# int8/16/32/64：代表与1B/2B/4B/8B相同的8位/16位/32位/64位整数
# uint8/16/32/64：代表与1B/2B/4B/8B相同的8位/16位/32位/64位无符号整数
# float_：浮点数类型，等同于float64
# float16/32/64：半精度浮点数（1个符号位，5个指数位，10个尾数位）；单精度浮点数（1个符号位，8个指数位，23个尾数位）；双精度浮点数（1个符号位，11个指数位，52个尾数位）
# complex：复数类型，complex128复数类型的简写
# complex64/128：双32位浮点数（实数部分、虚数部分）；双64位浮点数（实数部分、虚数部分）
# str：表示字符串类型
# string：表示字节串类型，也就是bytes类型

import numpy as np

In [35]:
# numpy的默认整数类型是int64
a=np.array([1,2,3,4])
print(a,a.dtype)

# 将数组中的数据存储为整数类型int8
a=np.array([1,2,3,4],dtype=np.int8)
print(a,a.dtype)

[1 2 3 4] int64
[1 2 3 4] int8


In [36]:
# 将数组中的数据存储为双精度浮点类型float64
a=np.array([1,2,3,4],dtype=np.float64)
print(a,a.dtype)

# 将数组中的数据存储为自适应精度浮点类型float_
a=np.array([1,2,3,4],dtype=np.float_)
print(a,a.dtype)

[1. 2. 3. 4.] float64
[1. 2. 3. 4.] float64


In [37]:
# 将数组中的数据存储为布尔类型
a=np.array([0,1,2,3,4],dtype=np.bool_)
print(a)

[False  True  True  True  True]


In [38]:
# str_与string_区别
# Python3内存中统一使用Unicode，记录到硬盘或者编辑文本的时候均转换成UTF-8
str1=np.array([1,2,3,4,5,6],dtype=np.str_)
string1=np.array([1,2,3,4,5,6],dtype=np.string_)
str2=np.array(['我们',2,3,4,5,6],dtype=np.str_)
print(str1,str1.dtype)
print(string1,string1.dtype)
print(str2,str2.dtype)

['1' '2' '3' '4' '5' '6'] <U1
[b'1' b'2' b'3' b'4' b'5' b'6'] |S1
['我们' '2' '3' '4' '5' '6'] <U2


In [39]:
# 2.定义结构化数据，数据类型标识码如下：
# b：布尔型；i：带符号整形；u：无符号整形；f：浮点型；c：复数浮点型；m：时间间隔；M：日期时间；
# O：Python对象；S：字节串；a：字符串；U：Unicode；V：原始数据

# 首先创建结构化数据类型
dt=np.dtype([('age','i1')])     # i1即int8
print(dt)
# 将数据类型dt应用于ndarray对象
students=np.array([(18),(19)],dtype=dt)     # dtype=自定义结构化数据类型dt
print(students,students.dtype,students.ndim)
print(students['age'],students['age'].dtype)

[('age', 'i1')]
[(18,) (19,)] [('age', 'i1')] 1
[18 19] int8


In [40]:
# 定长字符串：不灵活效率高；变长字符串：灵活但效率低
# 创建字符串数组时，会取最大长度
a=np.array(['a','ab','abc','我们','我们是谁','12345'],dtype=np.str_)
print(a,a.dtype)

# 当修改内部元素时，也只能保留长度为5的字符串
a[1]='123456'
print(a,a.dtype)

# 显示设置每个字符串元素的最大长度
a=np.array(['a','ab','abc','我们','我们是谁','12345'],dtype='U8')
print(a,a.dtype)
a[1]='123456'
print(a,a.dtype)
a[1]='123456789'
print(a,a.dtype)

# 还可接受可变长的字符串，修改数据类型dtype=object
a=np.array(['a','ab','abc','我们','我们是谁','12345'],dtype=object)
print(a,a.dtype)
a[1]='123456'
print(a,a.dtype)
a[1]='123456789'
print(a,a.dtype)


['a' 'ab' 'abc' '我们' '我们是谁' '12345'] <U5
['a' '12345' 'abc' '我们' '我们是谁' '12345'] <U5
['a' 'ab' 'abc' '我们' '我们是谁' '12345'] <U8
['a' '123456' 'abc' '我们' '我们是谁' '12345'] <U8
['a' '12345678' 'abc' '我们' '我们是谁' '12345'] <U8
['a' 'ab' 'abc' '我们' '我们是谁' '12345'] object
['a' '123456' 'abc' '我们' '我们是谁' '12345'] object
['a' '123456789' 'abc' '我们' '我们是谁' '12345'] object
