In [6]:
import numpy as np

# 元素为整数
ar1=np.arange(10)
print(ar1)

# 元素为浮点数
ar2=np.arange(3.1)
print(ar2)

# 可通过dtype指定类型
ar3=np.arange(5,dtype=float)
print(ar3)

# 会报错，range参数必须是int类型
# range(3.1)
ar4=range(5)
print(ar4)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3.]
[0. 1. 2. 3. 4.]
range(0, 5)


In [14]:
# 设置起始值、终止值、步长
ar1=np.arange(10,20,2)
print(ar1)

# 此时起始值=20,终止值=2,无步长
ar2=np.arange(20,2)
print(ar2)

# 指定参数赋值
ar2=np.arange(20,step=2)
print(ar2)

# 如果数组太大而无法打印，numpy会自动跳过数组中心部分，只打印边角
ar3=np.arange(10000)
print(ar3)

[10 12 14 16 18]
[]
[ 0  2  4  6  8 10 12 14 16 18]
[   0    1    2 ... 9997 9998 9999]


In [19]:
# 想得到一个长度为3,从0.1开始的间隔为0.1的数组
np.arange(0.1,0.4,0.1)

array([0.1, 0.2, 0.3, 0.4])