In [3]:
import numpy as np

# shape属性：包含数组维度的元组
ar1=np.array([1,2,3,4,5,6])
print("一维数组：",ar1.shape)

ar2=np.array([[1,2,3],[4,5,6]])
print("二维数组：",ar2.shape)

ar3=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [11,22,33],
        [44,55,66]
    ]
]
)
print("三维数组：",ar3.shape)

一维数组： (6,)
二维数组： (2, 3)
三维数组： (2, 2, 3)


In [ ]:
# ndarray.reshape()：调整数组维度,参数是包含新数组各个维度长度的元组/列表，返回调整后的副本，不改变原ndarray
ar=np.array([1,2,3,4,5,6])
print("一维数组：",ar.shape)

# ar4=ar.reshape([2,3])
ar4=np.reshape(ar,(2,3))
print("ar4的形状:",ar4.shape)

一维数组： (6,)
ar4的形状: (2, 3)


In [ ]:
# numpy.resize(a,new_shape):调整数组维度,参数是包含新数组各个维度长度的元组/列表，如果新数组大于原数组,则用原数组重复填充
ar=np.array([[0,1],[2,3]])
ar5=np.resize(ar,(2,3))
print(ar5)

# resize(new_shape):调整数组维度,参数是包含新数组各个维度长度的元组/列表
ar6=np.resize(ar,(2,1))
print(ar6)

[[0 1 2]
 [3 0 1]]
[[0]
 [1]]


In [ ]:
# ndarray.ndim：数组的维度（轴的数量），是一个标量
print("ar1的维度:",ar1.ndim)
print("ar2的维度:",ar2.ndim)
print("ar3的维度:",ar3.ndim)

# ndarray.size：数组元素的总个数
print("ar1的元素个数:",ar1.size)
print("ar2的元素个数:",ar2.size)
print("ar3的元素个数:",ar3.size)

# ndarray.dtype：数组元素的数据类型
print("ar1的元素类型:",ar1.dtype)
ar2=np.array([[1.0,2,3],[4,5,6]])   # 以最大的数据类型生成array
print("ar2的元素类型:",ar2.dtype)

ar1的维度: 1
ar2的维度: 2
ar3的维度: 3
ar1的元素个数: 6
ar2的元素个数: 6
ar3的元素个数: 12
ar1的元素类型: int64
ar2的元素类型: float64


In [22]:
# astype()：数据类型转换，返回数据类型修改后的数组，但原数组的类型不改变
ar=np.array([1.1,2.2])
print("ar的元素类型:",ar.dtype)
print("astype()修改ar的数据类型：",ar.astype('float32').dtype)
print("原ar的元素类型:",ar.dtype)

# 正确操作，修改类型后应再次赋值
ar=ar.astype('float32')
print("再次赋值后ar的元素类型:",ar.dtype)

ar的元素类型: float64
astype()修改ar的数据类型： float32
原ar的元素类型: float64
再次赋值后ar的元素类型: float32


In [ ]:
# ndarray.itemsize：以占用字节数形式返回数组中每个元素的大小
ar=np.array([1.1,2.2,3.3])
print('dtype：',ar.dtype,'itemsize：',ar.itemsize)

ar=np.array([1,2,3,4,5])
print('dtype：',ar.dtype,'itemsize：',ar.itemsize)

dtype： float64 itemsize： 8
dtype： int64 itemsize： 8
