In [21]:
# 注意：默认为numpy包设置别名np
import numpy as np

In [22]:
# array()：括号内可以是元组、列表、数组、迭代对象、生成器
np.array([1,2,3,4,5])
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [23]:
# 元组
np.array((1,2,3,4,5))

array([1, 2, 3, 4, 5])

In [24]:
# 数组
a=np.array([1,2,3,4,5])
np.array(a)

array([1, 2, 3, 4, 5])

In [ ]:
# 迭代对象
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# 生成器
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
# 创建10以内偶数的数组，if条件语句放在生成器最后面（只能是一个if）
np.array([i for i in range(10) if(i%2==0)])

array([0, 2, 4, 6, 8])

In [28]:
# 列表中元素类型不相同
np.array([1,1,5,3,4,5,'5'])

array(['1', '1', '5', '3', '4', '5', '5'], dtype='<U21')

In [29]:
# 二维数组：嵌套序列（列表、元组均可）
np.array([[1,2,3],('a','b','c')])

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U21')

In [30]:
# 嵌套序列不同行元素数量不一样
ar=np.array([[1,2,3],('a','b','c','d')],dtype=object)
print(ar)
print(ar.ndim,ar.shape)

[list([1, 2, 3]) ('a', 'b', 'c', 'd')]
1 (2,)


In [31]:
# 嵌套序列不同行元素数量不一样
np.array([[1,2,3],[1,2,3,4]],dtype=object)

array([list([1, 2, 3]), list([1, 2, 3, 4])], dtype=object)

In [33]:
# dtype参数：指定元素数据类型（默认自动识别）
ar=np.array([1,2,3,4,5],dtype=float)
print(ar)
# 将小数直接转为int类型，将直接截断小数部分保留整数部分
ar=np.array([1.1,2.3,3.5,4.6,5.7],dtype=int)
print(ar)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


In [50]:
# copy参数：深拷贝，默认为True深拷贝
a=np.array([1,2,3,4,5])
b=np.array(a)
print('a:',id(a)," b:",id(b))
# 修改b的元素，a不会发生变化
b[0]=10
print('a:',a,' b:',b)
# 修改a的元素，b不会发生变化
a[1]=20
print('a:',a,' b:',b)

# copy=False：浅拷贝
a=np.array([1,2,3,4,5])
b=np.array(a,copy=False)
print('a:',id(a)," b:",id(b))
# 修改b的元素，a也会发生变化
b[0]=10
print('a:',a,' b:',b)
# 修改a的元素，b也会发生变化
a[1]=20
print('a:',a,' b:',b)

a: 139678445127312  b: 139678447368112
a: [1 2 3 4 5]  b: [10  2  3  4  5]
a: [ 1 20  3  4  5]  b: [10  2  3  4  5]
a: 139678445129136  b: 139678445129136
a: [10  2  3  4  5]  b: [10  2  3  4  5]
a: [10 20  3  4  5]  b: [10 20  3  4  5]


In [ ]:
# 数组的copy方法，也属于深拷贝
a=np.array([1,2,3,4,5])
b=a.copy()
print('a:',id(a)," b:",id(b))

a: 139678451721456  b: 139678451725584


In [44]:
# 直接赋值，视作浅拷贝，b和a指向同一内存地址
a=np.array([1,2,3,4,5])
b=a
print('a:',id(a)," b:",id(b))
# 修改b的元素，a也会发生变化
b[0]=10
print('a:',a,' b:',b)
# 修改a的元素，b也会发生变化
a[1]=20
print('a:',a,' b:',b)

a: 139679314789456  b: 139679314789456
a: [10  2  3  4  5]  b: [10  2  3  4  5]
a: [10 20  3  4  5]  b: [10 20  3  4  5]


In [46]:
# ndmin：用于指定数组维度
a=np.array([1,2,3,4,5],ndmin=2)
print(a.ndim)

2


In [49]:
# subok：=True，使用object的内部数据类型；=False，使用数组的数据类型（默认为False）
a=np.mat([1,2,3,4,5])
print(type(a))  # 输出矩阵类型

at=np.array(a,subok=True)
af=np.array(a)
print('at，subok=True：',type(at))
print('af，subok=False：',type(af))
print('a:',id(a)," at:",id(at)," af:",id(af))

<class 'numpy.matrix'>
at，subok=True： <class 'numpy.matrix'>
af，subok=False： <class 'numpy.ndarray'>
a: 139678451580224  at: 139678451572544  af: 139678447359568
