In [2]:
# ndarray对象内容可通过索引或切片访问/修改，与Python中list的切片操作一样；基于0~n的下标进行索引
# 区别在于ndarray数组切片是原始数组视图（切片执行的任何修改，原始数组也会跟着进行修改）；如果不想更改原始数组则需要进行显式复制.copy()
# 而Python的list切片是新数组试图（切片执行的任何修改，原始数组也会跟着进行修改）
import numpy as np

ar1=np.arange(10)
print(ar1)      # 从0开始
print(ar1[4])
print(ar1[-1])

[0 1 2 3 4 5 6 7 8 9]
4
9


In [3]:
# 对ar1切片，从索引2开始到索引8-1=7停止，间隔为2
ar2=ar1[2:8:2]
print(ar2)

[2 4 6]


In [4]:
# 对ar1切片，从索引2开始直到最后
ar3=ar1[2:]
print(ar3)

# 对ar1切片，从索引0开始直到索引7-1=6
ar4=ar1[:7]
print(ar4)

[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]


In [7]:
# 定义4行5列的数组
ar4_5=np.arange(20).reshape(4,5)
print(ar4_5)

# 返回ar4_5的秩（维数）
print(ar4_5.ndim)

# 切片为下一维度的一个元素，所以是一维数组
print(ar4_5[2])

# 二次索引取得一维数组的元素
print(ar4_5[2][2])
print(ar4_5[2,2])   # 等同于print(ar4_5[2][2])

print(ar4_5[1:])

print(ar4_5[:3])

print(ar4_5[:3:2])

# 在行位置使用省略号，返回值将包含所有行；在列位置使用省略号，返回值将包含所有列
print(ar4_5[...,1])     # [ 1  6 11 16]
# 相当于s=ar4_5[...]  s[1]
print(ar4_5[...][1])    # [5 6 7 8 9]

print(ar4_5[...,1:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
2
[10 11 12 13 14]
12
12
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
[ 1  6 11 16]
[5 6 7 8 9]
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


In [12]:
# 整数数组索引
x=np.array([
    [1,2],
    [3,4],
    [5,6]
])

# [0,1,2]代表行索引，[0,1,0]代表列索引；分别获取x[0][0]；x[1,1]；x[2][0]
y=x[[0,1,2],[0,1,0]]
print(y)

# 获取4*3数组的四个角上元素，对应的行索引是[0,0],[3,3]，对应的列索引是[0,2],[0,2]
x=np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,10,11]
])
r=np.array([[0,0],[3,3]]).reshape(4)
l=np.array([[0,2],[0,2]]).reshape(4)
y=x[r,l].reshape((2,2))
print(y)

x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b=x[1:3,1:3]
c=x[1:3,[1,2]]
d=x[...,1:]
print(b)
print(c)
print(d)

[1 4 5]
[[ 0  2]
 [ 9 11]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [17]:
# 创建一个8*8的国际象棋棋盘矩阵，黑块为0白块为1
Z=np.zeros((8,8),dtype=int)
print(Z)
Z[1::2,::2]=1
print(Z)
Z[::2,1::2]=1
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
# 布尔数组索引：输出结果需经过布尔运算，使用的高级索引方式
x=np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8],
    [9,10,11]
])

# 输出值>6的元素
print(x[x>6])

# 输出数组中的所有奇数
print(x[x%2==1])

# 将数组中的所有奇数值修改为-1
x[x%2==1]=-1
print(x)

# 筛选出指定区间内数据
print(x[(x>4)&(x<9)])
print(x[(x>4)|(x<9)])

[ 7  8  9 10 11]
[ 1  3  5  7  9 11]
[[ 0 -1  2]
 [-1  4 -1]
 [ 6 -1  8]
 [-1 10 -1]]
[6 8]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1]


In [ ]:
# 布尔数组作切片
a3_4=np.arange(12).reshape(3,4)
print(a3_4)

# 行变量存在3个元素
row1=np.array([False,True,True])
# 列变量存在3个元素
column1=np.array([True,False,True,False])

# a3_4是3行，作切片时也提供三个元素的数组，轴的长度一致
print(a3_4[row1])
print(a3_4[:,column1])

# 使用两个布尔数组作切片（两个一维布尔数组内的True个数相等）
print(a3_4[row1,column1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[ 4 10]
