In [ ]:
import numpy as np

# 设置起始值=1，终止值=10，元素个数为10
ar1=np.linspace(1,10,10)
print(ar1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# 实现输出0 0.5 1 1.5 2 2.5 3 3.5 4
ar2=np.linspace(0,4,9)
print(ar2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# 设置起始值=2.0，终止值=3.0，元素个数为5
ar3=np.linspace(2.0,3.0,num=5)
print(ar3)

[2.   2.25 2.5  2.75 3.  ]


In [16]:
# 设置起始值=2.0，元素个数为5，无终止值
ar4=np.linspace(2.0,3.0,num=5,endpoint=False)
print(ar4)

[2.  2.2 2.4 2.6 2.8]


In [19]:
# 设置retstep显示计算后的步长
ar5=np.linspace(2.0,3.0,num=5,retstep=True)
print(ar5,type(ar5))

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) <class 'tuple'>


In [21]:
# 设置起始值=2.0，元素个数为5，无终止值，retstep显示计算后的步长
ar6=np.linspace(2.0,3.0,num=5,endpoint=False,retstep=True)
print(ar6)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)
