In [2]:
import numpy as np

m1=np.arange(20).reshape(4,5)
print(m1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [3]:
# 1.mean()：求平均值
# 默认求出数组所有元素的平均值
print(m1.mean())

# 求某一维度的平均值，设置axis参数
# axis=0从上往下计算；axis=1从左往右计算
print(m1.mean(axis=0))
print(m1.mean(axis=1))

9.5
[ 7.5  8.5  9.5 10.5 11.5]
[ 2.  7. 12. 17.]


In [4]:
# 2.np.median：中位数（中点数、中值）
# 按顺序排列的一组数据中居于中间位置的数；代表一个样本、种群或概率分布中的一个数值
ar1=np.array([1,3,5,6,8])       # 奇数个元素，直接取最中间
print(np.median(ar1))

ar2=np.array([1,3,5,6,8,9])     # 偶数个元素，取中间两个元素的平均数
print(np.median(ar2))

5.0
5.5


In [5]:
# 3.ndarray.std：求标准差
# 标准差定义：总体各单位标准值与其平均数离差平方的算术平均数的平方根（有计量单位，是表示精确度的重要指标）
# 在概率统计中最常使用，作为统计分布程度上的测量，是反映一组数据离散程度最常用的一种量化形式（数据平均值分散程度的一种度量）
a=np.array([95,85,75,65,55,45])
b=np.array([73,72,71,69,68,67])

# 利用numpy函数np.std()求标准差
print(np.std(a))
print(np.std(b))

# 按定义求标准差
import math
math.sqrt(np.sum(((a-np.mean(a))**2)/a.size))

17.07825127659933
2.160246899469287


17.07825127659933

In [ ]:
# 4.ndarray.var()：求方差（无计量单位）
a=np.array([95,85,75,65,55,45])
b=np.array([73,72,71,69,68,67])

# 利用numpy函数np.var()求方差
print(np.var(a))
print(np.var(b))

291.6666666666667
4.666666666666667


In [ ]:
# 5.ndarray.max()：求最大值
print(m1)
print(m1.max())

# 求某一维度的最大值，设置axis参数
# axis=0从上往下查找；axis=1从左往右查找
print(m1.max(axis=0))
print(m1.max(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
19
[15 16 17 18 19]
[ 4  9 14 19]


In [ ]:
# 6.ndarray.min()：求最小值
print(m1)
print(m1.min())

# 求某一维度的最小值，设置axis参数
# axis=0从上往下查找；axis=1从左往右查找
print(m1.min(axis=0))
print(m1.min(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
0
[0 1 2 3 4]
[ 0  5 10 15]


In [ ]:
# 7.ndarray.sum()：求和
print(m1)
print(m1.sum())

# 求某一维度的总和，设置axis参数
# axis=0从上往下查找；axis=1从左往右查找
print(m1.sum(axis=0))
print(m1.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
190
[30 34 38 42 46]
[10 35 60 85]


In [13]:
# 8.numpy.average()：加权平均值
# 将各数值乘以相应的权数，然后求总和得到总体值，再除以总的单位数
average_a1=[20,30,50]

print(np.average(average_a1))   # 无权重时等同于numpy.mean()方法
print(np.mean(average_a1))

xiaoming=np.array([80,90,95])
xiaogang=np.array([95,90,80])
weights=np.array([0.2,0.3,0.5])     # 权重数组
# 分别计算小明和小刚的加权平均成绩
print(np.average(xiaoming,weights=weights))
print(np.average(xiaogang,weights=weights))

33.333333333333336
33.333333333333336
90.5
86.0
