In [3]:
import numpy as np

ar1=np.logspace(0,9,10,base=2)
print(ar1)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [7]:
# 先使用前3个参数，将[1,5]均匀分成3个数，得到[1,3,5]
# 然后利用base=2（默认是10）得到最终输出结果[2^1,2^3,2^5]
ar2=np.logspace(1,5,3,base=2)
print(ar2)

[ 2.  8. 32.]


In [9]:
# 取得1~2之间的10个常用对数
ar3=np.logspace(1.0,2.0,num=10)
print(ar3)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [12]:
ar4=np.linspace(1.0,2.0,num=10)
print(ar4)
10**ar4

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])