In [36]:
# loadtxt：读取.csv/.txt文件；参数如下：
# (1)fname：指定文件名称的字符串，支持压缩文件（.zip/.bz/.gz......）
# (2)dtype：数据类型，默认为float
# (3)comments：字符串/字符串组成的列表。表示注释字符集开始的标志，默认为#
# (4)delimiter：字符串分隔符
# (5)converters：字典，将特定列的数据转换为字典中对应的函数的浮点型数据（例：空值转换为0，默认为空）
# (6)skiprows：跳过特定行数据（例：跳过前一行标题/注释，默认为0）
# (7)usecols：元组，用来指定要读取数据的列，第一列为0，默认为空）
# (8)unpack：布尔型，指定是否转置数组，为True则转置
# (9)ndmin：整数型，指定返回的数组中至少包含特定维度的数组，可以取0，1，2，默认为0
# (10)encoding：编码，确认文件是gbk还是utf-8格式
# 返回值：从文件中读取的数组

import numpy as np

In [37]:
# 1.读取.txt文件，可以不用设置分隔符（空格/制表符）
data=np.loadtxt('./data/data1.txt',dtype=np.int32)
print(data,data.dtype,data.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] int32 (3, 10)


In [38]:
# 2.读取.csv文件，设置分隔符，默认为','
data=np.loadtxt('./data/csv_test.csv',dtype=np.int32,delimiter=',')
print(data,data.dtype,data.shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] int32 (3, 10)


In [41]:
# 3.不同列标识不同信息，数据读取
# 因为不同列数据标识的含义和类型不同，所以需要自定义数据类型
user_info=np.dtype([('name','U10'),('age','i1'),('gender','U1'),('height','i2')])
print(user_info)

# 使用自定义的数据类型读取数据
data=np.loadtxt('./data/has_title.txt',dtype=user_info,skiprows=1,encoding='utf-8')
print(data)

data=np.loadtxt('./data/has_title.txt',dtype=int,skiprows=1,usecols=(1,3),encoding='utf-8')
print(data)

user_info=np.dtype([('age','i1'),('height','i2')])
print(user_info)
data=np.loadtxt('./data/has_title.csv',dtype=user_info,skiprows=1,usecols=(1,3),delimiter=',')
print(data)

[('name', '<U10'), ('age', 'i1'), ('gender', '<U1'), ('height', '<i2')]
[('小王', 21, '男', 170) ('老王', 50, '男', 180) ('小红', 23, '女', 176)
 ('老红', 34, '女', 167)]
[[ 21 170]
 [ 50 180]
 [ 23 176]
 [ 34 167]]
[('age', 'i1'), ('height', '<i2')]
[(21, 170) (50, 180) (23, 176) (34, 167)]


In [44]:
user_info=np.dtype([('name','U10'),('age','i1'),('gender','U1'),('height','i2')])
data=np.loadtxt('./data/has_title.txt',dtype=user_info,skiprows=1,encoding='utf-8')

# 计算平均年龄
ages=data['age']
print(ages.mean())

# 计算女生的平均身高
isgirl=data['gender']=='女'
print(isgirl)
print(data['height'])
print(data['height'][isgirl])
girl_mean=np.mean(data['height'][isgirl])
print(girl_mean)
'{:.2f}'.format(girl_mean)

32.0
[False False  True  True]
[170 180 176 167]
[176 167]
171.5


'171.50'