In [ ]:
# 引入numpy
import numpy as np
# array()创建数组，括号内可以是列表、元组或其他数组（迭代对象），
print(np.array([1, 2, 3, 4, 5]))  # 列表
print(np.array((1, 2, 3, 4, 5)))  # 元组
a=np.array([1, 2, 3, 4, 5])  # 数组
print(np.array(a))  # 数组
print(np.array(range(5)))  # range对象
print(np.array([i**2 for i in range(5)]))  # 列表推导式（生成器）

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
[0 1 2 3 4]
[ 0  1  4  9 16]
