In [2]:
# 广播：numpy对不同形状的数组进行数值计算的方式
# 核心：对形状较小的数组，在横向/纵向上进行一定次数的重复，使其与形状较大的数组拥有相同的维度
# 1.所有输入数组都向其中最长的看齐，缺少的维度先用1补齐；
# 2.输出数组的形状是输入数组形状在各个维度上的最大值；
# 3.输入数组某个维度和输出数组对应维度长度相同/长度为1时，该数组才能用来计算；
# 4.输入数组某个维度长度为1时，沿着该维度计算都用第1组值

import numpy as np

a=np.array([
    [0,0,0],
    [10,10,10],
    [20,20,20],
    [30,30,30]
])
b=np.array([1,2,3])
# b最终变为[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]
print(a+b)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [7]:
# 也可以如下简单理解：
# 1.两个数组维度大小右对齐，然后比较对应维度上的数值
# 2.如果数值相等/其中有一个为1/为空，则可以进行广播运算
# 3.输出的维度大小为取数值大的数值，否则不能进行数组运算

# 数组a大小为(2,3)
a=np.arange(6).reshape(2,3)
print('a:',a)
# 数组b大小为(1,)
b=np.array([5])
print('b:',b)
# 2   3
#     1
# ——————
# 2   3
c=a*b
print(c)

# 数组a大小为(2,1,3)
a=np.arange(6).reshape(2,1,3)
print('a:',a)
# 数组b大小为(4,1)
b=np.arange(4).reshape(4,1)
print('b:',b)
# 2   1   3
#     4   1
# ——————————
# 2   4   3
c=a+b
print(c)

a: [[0 1 2]
 [3 4 5]]
b: [5]
[[ 0  5 10]
 [15 20 25]]
a: [[[0 1 2]]

 [[3 4 5]]]
b: [[0]
 [1]
 [2]
 [3]]
[[[0 1 2]
  [1 2 3]
  [2 3 4]
  [3 4 5]]

 [[3 4 5]
  [4 5 6]
  [5 6 7]
  [6 7 8]]]


In [ ]:
# 数组a大小为(2,1,3)
a=np.arange(6).reshape(2,1,3)
print('a:',a)
# 数组b大小为(4,2)
b=np.arange(8).reshape(4,2)
print('b:',b)
# 2   1   3
#     4   2
# ——————————
# 2   4   X
# 数组之间必须满足广播规则，否则就会报错；事实上相同大小的数组运算也遵循广播机制
c=a+b
print(c)

a: [[[0 1 2]]

 [[3 4 5]]]
b: [[0 1]
 [2 3]
 [4 5]
 [6 7]]


ValueError: operands could not be broadcast together with shapes (2,1,3) (4,2) 