In [6]:
import numpy as np

# 元素为整数
ar1=np.arange(10)
print(ar1)

# 元素为浮点数
ar2=np.arange(3.1)
print(ar2)

# 可通过dtype指定类型
ar3=np.arange(5,dtype=float)
print(ar3)

# 会报错，range参数必须是int类型
# range(3.1)
ar4=range(5)
print(ar4)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3.]
[0. 1. 2. 3. 4.]
range(0, 5)


In [14]:
# 设置起始值、终止值、步长
ar1=np.arange(10,20,2)
print(ar1)

# 此时起始值=20,终止值=2,无步长
ar2=np.arange(20,2)
print(ar2)

# 指定参数赋值
ar2=np.arange(20,step=2)
print(ar2)

# 如果数组太大而无法打印，numpy会自动跳过数组中心部分，只打印边角
ar3=np.arange(10000)
print(ar3)

[10 12 14 16 18]
[]
[ 0  2  4  6  8 10 12 14 16 18]
[   0    1    2 ... 9997 9998 9999]


In [ ]:
ar1=np.arange(0,200+1,3)
print(ar1,len(ar1))

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198] 67
